### ISSUE TITLE
1.20 is not working

### ISSUE THREAD

**Issue by Jeenvries** [maxsupermanhd/meteor-villager-roller#26]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Meteor Villager Roller' (meteor-villager-roller) 1.3.9+mc1.20-rev.a6b847d with any version that is compatible with:
		 - minecraft 1.20.1
Unmet dependency listing:
	 - Mod 'Meteor Villager Roller' (meteor-villager-roller) 1.3.9+mc1.20-rev.a6b847d requires version 1.20 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by maxsupermanhd** [comment]
1.20 is not a 1.20.1 (wow shocker)
Version for 1.20.1 will come soon
